# Generated by Django 5.1.2 on 2024-10-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_calculator', '0002_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='zakat_amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
