# Generated by Django 5.1.2 on 2024-10-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_calculator', '0003_alter_subcategory_zakat_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='zakat_amount',
            new_name='zakat_percentage',
        ),
    ]
