# Generated by Django 5.1.2 on 2024-10-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_calculator', '0004_rename_zakat_amount_subcategory_zakat_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='varlik',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='zekat',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
