# Generated by Django 5.1.2 on 2024-10-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_calculator', '0005_subcategory_varlik_subcategory_zekat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='varlik',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='zekat',
        ),
    ]
