# Generated by Django 5.1.2 on 2024-10-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_calculator', '0006_remove_subcategory_varlik_remove_subcategory_zekat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='zakat_percentage',
        ),
    ]
