# Generated by Django 5.1.2 on 2024-10-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_calculator', '0007_remove_subcategory_zakat_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
