# Generated by Django 5.1.2 on 2024-10-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_calculator', '0008_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='abreviation',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
