# Generated by Django 5.1.2 on 2024-10-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_calculator', '0009_currency_abreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='info_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='info_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='info_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='info_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='info_tr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
